-- This script contains the CREATE TABLE statements for the project's database schema.
-- Please run this script in your Supabase project's SQL Editor to set up the tables.

-- 1. Create the users table
-- This table will store the primary user information, linked by their unique Telegram ID.
CREATE TABLE public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id TEXT NOT NULL UNIQUE,
  full_name TEXT,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create the gameprofiles table
-- This table holds the data related to a user's game progress.
CREATE TABLE public.gameprofiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  balance INT NOT NULL DEFAULT 500,
  spins INT NOT NULL DEFAULT 3,
  is_vip BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create the tasks table
-- This table stores the individual tasks for each game profile.
CREATE TABLE public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id BIGINT NOT NULL REFERENCES public.gameprofiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  reward INT NOT NULL,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add comments to the tables and columns for clarity
COMMENT ON TABLE public.users IS 'Stores basic user information, identified by their Telegram ID.';
COMMENT ON TABLE public.gameprofiles IS 'Stores game-specific data for each user.';
COMMENT ON TABLE public.tasks IS 'Stores tasks assigned to each user''s game profile.';
